#! /bin/sh

set -e

PIDFILE=/var/run/mf910-reboot.pid
case "$1" in
  start|restart)
    start-stop-daemon -K -p $PIDFILE || true
    echo -n "Starting mf910-reboot.sh: "
    start-stop-daemon -S -b -a /usr/bin/mf910-reboot.sh -p $PIDFILE -m
    echo "done"
    ;;
  stop)
    echo -n "Stopping mf910-reboot.sh: "
    start-stop-daemon -K -p $PIDFILE || true
    echo "done"
    ;;
  *)
    echo "Usage mf910-reboot { start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0

