#!/bin/bash

BASEDIR=/monroe/usage

if [ "$1" == "config" ]; then
  echo "graph_title Interface RX/TX";
  for IF in "eth0" "wlan0" "usb0" "usb1" "usb2" "wwan0" "wwan2"; do
    echo "${IF}RXTX.label $IF data (grand total)";
    echo "${IF}RX.label $IF received (total)";
    echo "${IF}TX.label $IF sent (total)";
    echo "${IF}RXMonroe.label $IF received (monroe)";
    echo "${IF}TXMonroe.label $IF sent (monroe)";
    echo "${IF}RXHost.label $IF received (host)";
    echo "${IF}TXHost.label $IF sent (host)";
  done
  for IF in "usb0" "usb1" "usb2"; do
    echo "${IF}RXZTE.label $IF received (ZTE)";
    echo "${IF}TXZTE.label $IF sent (ZTE)";
    echo "${IF}RXZTEMonthly.label $IF received (ZTE, monthly)";
    echo "${IF}TXZTEMonthly.label $IF sent (ZTE, monthly)";
  done
else
  for IF in "eth0" "wlan0" "usb0" "usb1" "usb2" "wwan0" "wwan2"; do
    RX=$(cat $BASEDIR/$IF.rx.total 2>/dev/null || echo "-1")
    RXNS=$(cat $BASEDIR/netns/$IF.rx.total 2>/dev/null || echo "-1")
    RXTOTAL=$(($RX + $RXNS))
    TX=$(cat $BASEDIR/$IF.tx.total 2>/dev/null || echo "-1")
    TXNS=$(cat $BASEDIR/netns/$IF.tx.total 2>/dev/null || echo "-1")
    TXTOTAL=$(($TX + $TXNS))
    GRAND=$(($RXTOTAL + $TXTOTAL))
    
    echo "${IF}RXTX.value $GRAND"
    echo "${IF}RX.value $RXTOTAL"
    echo "${IF}TX.value $TXTOTAL"
    echo "${IF}RXHost.value $RX"
    echo "${IF}TXHost.value $TX"
    echo "${IF}RXMonroe.value $RXNS"
    echo "${IF}TXMonroe.value $TXNS"
  done
  for IF in "usb0" "usb1" "usb2"; do
    DATA=$(curl -s 'http://192.168.0.1/goform/goform_get_cmd_process?multi_data=1&cmd=realtime_rx_bytes,realtime_tx_bytes,monthly_rx_bytes,monthly_tx_bytes' -H 'Referer: http://192.168.0.1/index.html' --interface $IF);
    if [ ! -z "$(echo $DATA|grep rx_bytes)" ]; then
      RXZTE=$(echo $DATA|jq -r '.realtime_rx_bytes');
      TXZTE=$(echo $DATA|jq -r '.realtime_tx_bytes');
      RXZTE_MON=$(echo $DATA|jq -r '.monthly_rx_bytes');
      TXZTE_MON=$(echo $DATA|jq -r '.monthly_tx_bytes');
    else
      RXZTE=-1; TXZTE=-1; RXZTE_MON=-1; TXZTE_MON=-1;
    fi;
    echo "${IF}RXZTE.value $RXZTE";
    echo "${IF}TXZTE.value $TXZTE";
    echo "${IF}RXZTEMonthly.value $RXZTE_MON";
    echo "${IF}TXZTEMonthly.value $TXZTE_MON";
  done;
fi
