#!/bin/sh

rm /tmp/metadata.db || true
systemctl enable metadata-exporter || true
systemctl restart  metadata-exporter || true
systemctl enable metadata-timeloop || true
systemctl restart  metadata-timeloop || true
