#!/bin/sh

rm /tmp/metadata.db || true
systemctl enable metadata-exporter || true
systemctl start  metadata-exporter || true
systemctl enable metadata-timeloop || true
systemctl start  metadata-timeloop || true
